configuration: Realse

pull_request:
 do_not_increase_build_number: true

#Resotre Nuget package before running MSBuil
before_build:
- nuget restore

#package Web Application Build 
build:
 verbosity: minimal
 publish_wap: true
